# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f88a64bc1e2b858603037ae2769611eb87b31eccae5a132c79b462fab39fdbf6b3dcb6cb2ddb74dfb33435ed9c175af9b588e66bd4485202d7e14f5c645686

test:
  secret_key_base: a3cbaa8ae6db5b8c5e09143079cc39a78d9ba5a94d5f457a226ea652782706e813d90951b736340f7e472d30eb1e9b4676087feace0f410a3f44a82c1679059d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
